name : Postmam Collection Workflow

on:
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
     - cron : 30 02 * * * # 8am IST
     - cron : 00 14 * * * # 7.30pm IST
     - cron : 00 06 * * 1-5 # 11.30pm IST Monday to Friday

jobs:
  run-postman-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v6.0.1

      - name: Install Nodejs and npm
        uses: actions/setup-node@v6.0.0
        with:
          node-version: '22'

      - name: Install Newman and Html-extra globally
        run: |
             npm install -g newman
             npm install -g newman-reporter-htmlextra

      - name: Run the Postman Collection with NewMan
        run: |
             newman run 'Inwarranty-flow Collection.postman_collection.json' \
             -e QA.postman_environment.json \
             -d testData.csv \
             -r cli,htmlextra
      
      - name: Newman Report
        if: always() # ensure that the archive executed whether the previous step has passed or not
        uses: actions/upload-artifact@v5.0.0
        with:
          name: Newman Report
          path: newman/*html

      - name: Creating git hub page branch
        if: always()
        uses: peaceiris/actions-gh-pages@v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: newman/










